VM_MEMORY = 2*1024
VM_CORES = 1

Vagrant.configure('2') do |config|

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--memory", VM_MEMORY]
    v.customize ["modifyvm", :id, "--cpus", VM_CORES]
  end

  config.vm.define "openwhisk" do |openwhisk|
    openwhisk.vm.hostname='openwhisk'

    # Download a Ubuntu image before starting.
    openwhisk.vm.box = "ubuntu/trusty-server-cloudimg-amd64"

    # Edit as necessary.
    openwhisk.vm.synced_folder "/Users/user/owplan", "/home/vagrant/owplan"
    
    openwhisk.ssh.insert_key = true
  end

end
